[package]
name = "buckets"
version = "0.1.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/frogtd/buckets"
license = "MIT OR Unlicense"
description = "O(n) integer sort"
keywords = ["radix"]
categories = ["algorithms"]

[dependencies]
